languageCode: en-us
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: Hune
description: Browse multiple web development sites at the same time.
baseURL: /
theme: hune
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
googleAnalytics: 
paginate: 40
outputs:
  home:
  - HTML
  - RSS
  - JSON
  section:
    - HTML
    - RSS
 
disableKinds:
  - taxonomyTerm
params:
  description: Browse multiple web development sites at the same time.
  favicon: img/favicon.png
  images:
    - img/home.png
  cta:
    title: Add my site
    url: 'https://github.com/cioranique/hune'
blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
# menu:
#   main:
#   - identifier: contribute
#     title: ThÃªm links
#     url: /pages/about.html
taxonomies:
  topic: topic
  site: site
  # tags: tags
  category: category
